### PR TITLE
swat test suite for nestoria API

### PR DESCRIPTION
**Pull request by melezhik**
Hi @kaoru !  This is simple test suite for  nestoria API written on [swat](https://github.com/melezhik/swat).
Run this as follows:

```
$ cd swat-test/
$ carton exec swat

```

on my laptop output looks like:

```
/home/vagrant/.swat/.cache/10570/prove/search_listings/00.GET.t ..
ok 1 - sleep for one second
ok 2 - GET http://api.nestoria.co.uk/api'/?place_name=soho&action=search_listings&encoding=json&country=uk&listing_type=buy&pretty=1' succeeded
# response saved to /home/vagrant/.swat/.cache/10570/prove/0BPjgsPo3p
ok 3 - GET '/?place_name=soho&action=search_listings&encoding=json&country=uk&listing_type=buy&pretty=1' returns 200 OK
ok 4 - GET '/?place_name=soho&action=search_listings&encoding=json&country=uk&listing_type=buy&pretty=1' returns | "response" : {
ok 5 - GET '/?place_name=soho&action=search_listings&encoding=json&country=uk&listing_type=buy&pretty=1' returns | "application_response_code" : "100"
1..5
ok
/home/vagrant/.swat/.cache/10570/prove/echo/00.GET.t .............
ok 1 - sleep for one second
ok 2 - GET http://api.nestoria.co.uk/api'/?action=echo&encoding=json&foo=bar&pretty=1' succeeded
# response saved to /home/vagrant/.swat/.cache/10570/prove/Uq7_HUKQpV
ok 3 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns 200 OK
ok 4 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "request" : {
ok 5 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "action" : "echo",
ok 6 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "encoding" : "json",
ok 7 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "foo" : "bar",
ok 8 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "pretty" : "1",
ok 9 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "sort" : "nestoria_rank"
ok 10 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | },
ok 11 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "response" : {
ok 12 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "action" : "echo",
ok 13 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' matches | "created_http" : ".*",
ok 14 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' matches | "created_unix" : \d+,
ok 15 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "encoding" : "json",
ok 16 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "foo" : "bar",
ok 17 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "pretty" : "1",
ok 18 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "sort" : "nestoria_rank",
ok 19 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "status_code" : "200",
ok 20 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "status_text" : "OK",
ok 21 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | "we_are_hiring" : "We are hiring programmers! http://lokku.com/jobs"
ok 22 - GET '/?action=echo&encoding=json&foo=bar&pretty=1' returns | }
1..22
ok
All tests successful.
Files=2, Tests=27, 23 wallclock secs ( 0.04 usr  0.00 sys +  0.17 cusr  0.02 csys =  0.23 CPU)
Result: PASS

```

[SWAT](https://github.com/melezhik/swat) is a flexible framework for rapid web tests development. If this this example sounds interesting  we could talk about possible co-working. Thanks.

Possible cooperation points:
- functional, blackbox testing for Nestoria API using swat
- swat automated tests of Nestoria API for the sake of monitoring and services health checks

### CODE REVIEW

**Comment by melezhik** [comment]
And ... to write this example it took  me a 5-10 minutes , it is very simple, more complicated checks with swat are doable ...

**Comment by kaoru** [comment]
@melezhik wow thanks for your work. I'll take a look and probably merge this this week :-)

**Comment by melezhik** [comment]
@kaoru  sounds good :) this was not even intended to be merged , I used github MR as the fastest way to "deliver" my idea. 

As swat does not depend on WebService::Nestoria::Search , swat tests for Nestoria-API could be placed somewhere else, and if you like the idea we could discuss a further collaboration ...

**Comment by melezhik** [comment]
Hi @kaoru , have you managed to look at swat pages? just want to hear what do you think? Thanks.

**Comment by melezhik** [comment]
Hi, sorry to bother you, any news here?

**Comment by kaoru** [comment]
Hi @melezhik, sorry for the delay in getting back to you.

I took a look at your swat tests and I'm not sure I like them... relying on the key order in a JSON response in particular seems like it could be dangerous, it works in the case of WebService::Nestoria::Search because it does sort the keys but there's no requirement to do so. Plus you're relying pretty heavily on the pretty=1 flag too.

The second big issue I have is that the two files get.txt and hook.pm are separate. I'd prefer to be able to glance and see the request and the response at the same time. It's also strange that hook.pm claims to be a ".pm" file, but has no package declaration.

Finally, I don't like having the tests in "swat-test" rather than "t", that means that no CPAN Testers bots or Travis CI instances will run the swat tests. I would recommend you put them under t/swat-test/ with a .t file so that a 'make test' or a 'prove -l -r' does the right thing.

Positively, I do like that you're using cpanfile and carton, and it looks like https://github.com/melezhik/swat has good docs.

Hope you find my feedback useful. All the best!

Alex

**Comment by melezhik** [comment]
Hi Alex. Really appreciates your comments. My follow up:

1. Concerning json sorted keys and pretty flag comment. I imply that a tested application follow some structure expected at test code. It is always a not a big deal, just takes some discipline for developers. And this is one of principle of test driven development. 


2. Separating request logic from response check logic I instead consider as one great benefit of swat design. It might be "uncomfortable" for the moment , but after little practice you may see a goodness of such an approach, splitting into different parts always make your code simpler and speeds up tests development at times. Please take a look at [swat downstream stories](https://github.com/melezhik/swat#upstream-and-downstream-stories) feature to see evolution of this idea.


3. Yes hook.pm names might be tricky, agreed , for some historical reasons I chose this name. But in general, one could place any perl code there and perl packages as well. From other side one may look at hook.pm as  ( perl ) module file in a sense that code from hook.pm will be automatically loaded into test, like when someone say "use foo::bar" .


4. Swat doesn't "insist" on specific name for test directory, I chose a swat-test to not interfere with existed t/ stuff. From other hand swat tests is not a regular perl tests which could be run directly by prove. But swat produce the same TAP output as prove does, also swat consumes the same options that prove has ( well,  under the hood  swat delegates a final test execution to prove ). 

Yes swat could not be integrated into cpan distribution workflow out of the box. And even though such an integration is achievable with some efforts, I am still not sure if it worth. Swat was NOT designed as unit tests framework, it's more like tool for rapid functional or smoke tests development of any web application. But if one need to distribute existed swat tests the simple solution I see now is a strait forward "git clone && carton && carton exec swat" way.


Anyway thanks again for reasonable criticism ,  I always welcome it (: , taking into account that not necessarily always people like what I do .

**Comment by kaoru** [comment]
Looks like you've thought about it a lot @melezhik :-) Thanks for sharing, and keep making open source contributions! :-)

**Comment by melezhik** [comment]
Yeah, sure , Alex, thanks for support ... 
 In case you need some rapid ( web ) test automation, please let me know ;-) ....

**Comment by melezhik** [comment]
Hi @kaoru , just FYI I am going to support json/xml responses soon - https://github.com/melezhik/swat#process-http-responses

It'd better way to test WebService-Nestoria-Search API, ? :)

**Comment by melezhik** [comment]
Hi @kaoru ! 

I have just updated https://github.com/melezhik/WebService-Nestoria-Search/tree/master/swat-test , as example of swat tests for  JSON application.  Now swat:
- json "safely"
- json_pretty irrelevant 
- sort order irrelevant
- code much simpler and cleaner 
- ability to check json structures using JSON module
- for general explanation of read this - https://github.com/melezhik/swat#process-http-responses
  Not because I want you to use it :smiley:  but in demonstration purposes , please take a look when you get a chance 

Regards

**Comment by kaoru** [comment]
Looks good @melezhik :) I like that JSON API authors get the choice if using the process-http-responses option or doing it raw like you showed in your first go at it.

Are you finding Swat is gaining popularity from your blog posts etc?

**Comment by melezhik** [comment]
Hi Alex! :smiley: 

> Are you finding Swat is gaining popularity from your blog posts etc?

Probably . it's hard estimate popularity of the product you develop. 30 stars on github, 1 at metacpan, no that many., huh :smile:  ? 

But I am confident swat will find it's place and could be used by many ...

**Comment by melezhik** [comment]
>  I like that JSON API authors get the choice if using the process-http-responses option or doing it raw like you showed in your first go at it.

yeah, idea of swat is to give a choice, by default you use plain text search | grep, if you need something more - create a response processor as adapter for specific data format ...

**Pull request closed without merging**
